apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  name: "Master2"
  criSocket: "/var/run/dockershim.sock"
  taints:
  - key: "node-role.kubernetes.io/master"
    effect: "NoSchedule"
  kubeletExtraArgs:
    cgroup-driver: "systemd"
  ignorePreflightErrors:
  - IsPrivilegedUser
localAPIEndpoint:
  advertiseAddress: "192.168.122.113"
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: "v1.23.1"
controlPlaneEndpoint: "192.168.122.254:6443"
#imageRepository: registry.aliyuncs.com/google_containers
clusterName: "master2"
certificatesDir: "/etc/kubernetes/pki"
dns:
  type: "CoreDNS"
networking:
  serviceSubnet: "10.96.0.0/16"
  podSubnet: "10.244.0.0/16"
  dnsDomain: "cluster.local"
etcd:
  external:
    endpoints:
    - "https://192.168.122.113:2379"
    - "https://192.168.122.146:2379"
    - "https://192.168.122.39:2379"
    caFile: "/etc/etcd/ssl/etcd.crt"
    certFile: "/etc/etcd/ssl/etcd_req.crt"
    keyFile: "/etc/etcd/ssl/etcd_req.key"
apiServer: 
  certSANs: 
  - "192.168.122.146"
  - "192.168.122.113"
  - "192.168.122.39"
  - "master1"
  - "master2"
  - "master3"
  - "node1"
  - "node2"
  - "node3"
  - "node4"
  - "node5"
  - "node6"
  - "node7"
  - "node8"
  - "arikan.base1.node1"
  - "arikan.base1.node2"
  - "arikan.base1.node3"
  - "arikan.base1.node4"
controllerManager:
#  extraArgs:
#    "node-cidr-mask-size": "20"
scheduler:
  extraArgs:
    address: "192.168.122.113"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
featureGates:
#  SupportIPVSProxyMode: true
mode: "ipvs"

