apiVersion: v1
kind: Secret
metadata:
  name: mysql-account-password
  namespace: rook-mysql
type: Opaque
data:
  mysql-root-password: az321654
  admin-account: YWRtaW4=
  admin-password: bXlzcWxfcGFzcw==
  backuper-account: YmFja3VwZXI=
  backuper-password: bXlzcWxfcGFzcw==
  bootstrap-account: Ym9vdHN0cmFwZXI=
  bootstrap-password: bXlzcWxfcGFzcw==
  replicator-account: cmVwbGljYXRvcg==
  replicator-password: bXlzcWxfcGFzcw==
