apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: rook-mysql
  labels:
    app: mysql
data:
  my.cnf: |
    # mysql configuration file
    [mysqld]
    #binlog_checksum=NONE
    #enforce_gtid_consistency=ON
    #gtid_mode=ON
    secure_file_priv=/var/lib/mysql    
    #innodb_force_recovery=6
    #innodb_read_only=0
    datadir=/var/lib/mysql
    #lower_case_table-names=1    

    !includedir /etc/mysql/conf.d/
    
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: rook-mysql
spec:
  ports:
  - name: mysql-service
    protocol: TCP
    port: 3306
  selector:
    app: mysql
  type: ClusterIP
