---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-default-cephfs-pvc
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: k8s-default-cephfs-sc
