---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-default-rbd-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: k8s-default-rbd-sc
